import React, { createContext, useContext, useState } from 'react';

const ProductContext = createContext();

export const ProductProvider = ({ children }) => {
    const [products] = useState([
        { id: 1, title: 'Apple MacBook Pro', description: '16-inch, 16GB RAM', image: '/img/mbp16-spacegray-gallery1-202110-1397x1397.jpg', lotInfo: 'Лот #123456, доступно 5 штук', shippingInfo: 'Доставка в течение 3-5 рабочих дней', price: 2400, category: 'Ноутбук' },
        { id: 2, title: 'Apple iPad Air', description: '10.9-inch, 256GB, Space Gray', image: '/img/img_0_1112_2554_0_1_KWMuV2.jpg', lotInfo: 'Лот #234567, доступно 3 штуки', shippingInfo: 'Бесплатная доставка', price: 700, category: 'Планшет' },
        { id: 3, title: 'Sony Headphones', description: 'Noise Cancelling, Wireless', image: '/img/100_1.jpg', lotInfo: 'Лот #345678, доступно 10 штук', shippingInfo: 'Доставка за 1 день, платно', price: 260, category: 'Наушники' },
        { id: 4, title: 'Samsung Galaxy S22 Ultra', description: '6.8-inch Dynamic AMOLED, 12GB RAM, 256GB Storage, Phantom Black', image: '/img/sm-s928_galaxys24ultra_front_titaniumblack_231109_result.jpg', lotInfo: 'Лот #789012, доступно 10 штук', shippingInfo: 'Бесплатная экспресс доставка', price: 1050, category: 'моб.Телефон' },
        { id: 5, title: 'Google Pixel 6', description: '6.4-inch AMOLED, 8GB RAM, 128GB Storage, Sorta Seafoam', image: '/img/5-1397x1397.jpg', lotInfo: 'Лот #543210, доступно 8 штук', shippingInfo: 'Доставка 2-3 рабочих дня', price: 800, category: 'моб.Телефон' },
        { id: 6, title: 'Dell XPS 13', description: '13.4-inch FHD+, Intel Core i7, 16GB RAM, 512GB SSD', image: '/img/41K3gWFID6L._AC_UF1000,1000_QL80_.jpg', lotInfo: 'Лот #654321, доступно 5 штук', shippingInfo: 'Стандартная доставка', price: 1200, category: 'Ноутбук' },
        { id: 7, title: 'Bose QuietComfort Earbuds', description: 'Noise Cancelling, Wireless, Triple Black', image: '/img/382915326.jpg', lotInfo: 'Лот #765432, доступно 15 штук', shippingInfo: 'Быстрая доставка', price: 290, category: 'Наушники' },
        { id: 8, title: 'Fitbit Charge 5', description: 'Fitness and Wellness Tracker, Black', image: '/img/417367540.jpg', lotInfo: 'Лот #876543, доступно 20 штук', shippingInfo: 'Доставка на следующий день', price: 200, category: 'Прочие' },
        { id: 9, title: 'Canon EOS R5', description: 'Full-Frame Mirrorless Camera, 45MP, 8K Video', image: '/img/87_600.jpg', lotInfo: 'Лот #987654, доступно 4 штуки', shippingInfo: 'Доставка 5-7 рабочих дней', price: 3500, category: 'Фото Камера' },
        { id: 10, title: 'NVIDIA GeForce RTX 3080', description: '10GB GDDR6X, Ray Tracing, 320-bit Memory Bus, PCI Express 4.0', image: '/img/b3080_web_tv8w.jpg', lotInfo: 'Лот #101010, доступно 7 штук', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 1500, category: 'Видеокарта' },
        { id: 11, title: 'Apple Watch Series 7', description: '41mm, Midnight Aluminum Case, Midnight Sport Band', image: '/img/apple-watch-series-7.jpg', lotInfo: 'Лот #111111, доступно 10 штук', shippingInfo: 'Доставка 1-2 рабочих дня', price: 400, category: 'Умные часы' },
        { id: 12, title: 'Microsoft Surface Pro 8', description: '13-inch, Intel Core i5, 8GB RAM, 128GB SSD', image: '/img/surface-pro-8.jpg', lotInfo: 'Лот #121212, доступно 6 штук', shippingInfo: 'Стандартная доставка', price: 1100, category: 'Планшет' },
        { id: 13, title: 'GoPro HERO10 Black', description: 'Action Camera, 5.3K60 Ultra HD Video, 23MP Photos', image: '/img/gopro-hero10.jpg', lotInfo: 'Лот #131313, доступно 8 штук', shippingInfo: 'Бесплатная доставка', price: 500, category: 'Камера' },
        { id: 14, title: 'Amazon Echo Show 10', description: '10.1" HD Smart Display with Motion and Alexa', image: '/img/echo-show-10.jpg', lotInfo: 'Лот #141414, доступно 12 штук', shippingInfo: 'Доставка 3-5 рабочих дней', price: 250, category: 'Умный дом' },
        { id: 15, title: 'JBL Charge 5', description: 'Portable Waterproof Speaker with Built-in Powerbank', image: '/img/jbl-charge-5.jpg', lotInfo: 'Лот #151515, доступно 20 штук', shippingInfo: 'Доставка 2-4 рабочих дня', price: 180, category: 'Аудио' },
        { id: 16, title: 'DJI Mini 2', description: 'Ultra-Light Foldable Drone with 4K Camera', image: '/img/dji-mini-2.jpg', lotInfo: 'Лот #161616, доступно 5 штук', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 450, category: 'Дрон' },
        { id: 17, title: 'PlayStation 5', description: 'Next-Gen Gaming Console, 825GB SSD, Ultra HD Blu-ray', image: '/img/ps5.jpg', lotInfo: 'Лот #171717, доступно 3 штуки', shippingInfo: 'Доставка 5-7 рабочих дней', price: 500, category: 'Игровая консоль' },
        { id: 18, title: 'Samsung QLED 4K TV', description: '55-inch, Quantum HDR, Smart TV', image: '/img/samsung-qled-tv.jpg', lotInfo: 'Лот #181818, доступно 7 штук', shippingInfo: 'Бесплатная доставка', price: 900, category: 'Телевизор' },
        { id: 19, title: 'Logitech MX Master 3', description: 'Advanced Wireless Mouse for Mac', image: '/img/logitech-mx-master-3.jpg', lotInfo: 'Лот #191919, доступно 15 штук', shippingInfo: 'Доставка 1-3 рабочих дня', price: 100, category: 'Аксессуары' },
        { id: 20, title: 'Apple AirPods Pro', description: 'Active Noise Cancellation, Wireless Charging Case', image: '/img/airpods-pro.jpg', lotInfo: 'Лот #202020, доступно 10 штук', shippingInfo: 'Экспресс-доставка за 1 день', price: 250, category: 'Наушники' },
        { id: 21, title: 'Canon EOS R6', description: 'Full-Frame Mirrorless Camera, 20MP, 4K Video', image: '/img/canon-eos-r6.jpg', lotInfo: 'Лот #212121, доступно 6 штук', shippingInfo: 'Доставка 5-7 рабочих дней', price: 2500, category: 'Фото Камера' },
        { id: 22, title: 'NVIDIA GeForce RTX 3090', description: '24GB GDDR6X, Ray Tracing, 384-bit Memory Bus, PCI Express 4.0', image: '/img/rtx-3090.jpg', lotInfo: 'Лот #222222, доступно 4 штуки', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 3000, category: 'Видеокарта' },
        { id: 23, title: 'Samsung Galaxy Tab S7', description: '11-inch, 128GB, Mystic Black', image: '/img/galaxy-tab-s7.jpg', lotInfo: 'Лот #232323, доступно 5 штук', shippingInfo: 'Бесплатная доставка', price: 650, category: 'Планшет' },
        { id: 24, title: 'Sony PlayStation 4 Pro', description: '1TB Console, Jet Black', image: '/img/ps4-pro.jpg', lotInfo: 'Лот #242424, доступно 8 штук', shippingInfo: 'Доставка 3-5 рабочих дней', price: 350, category: 'Игровая консоль' },
        { id: 25, title: 'Apple Mac Mini', description: 'Apple M1 Chip, 8GB RAM, 256GB SSD', image: '/img/mac-mini.jpg', lotInfo: 'Лот #252525, доступно 10 штук', shippingInfo: 'Бесплатная доставка', price: 700, category: 'ПК' },
        { id: 26, title: 'Microsoft Xbox Series X', description: '1TB Console, Black', image: '/img/xbox-series-x.jpg', lotInfo: 'Лот #262626, доступно 4 штуки', shippingInfo: 'Доставка 5-7 рабочих дней', price: 500, category: 'Игровая консоль' },
        { id: 27, title: 'Apple iPhone 13 Pro', description: '6.1-inch, 128GB, Sierra Blue', image: '/img/iphone-13-pro.jpg', lotInfo: 'Лот #272727, доступно 5 штук', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 1200, category: 'моб.Телефон' },
        { id: 28, title: 'Sony WH-1000XM4', description: 'Noise Cancelling, Wireless, Silver', image: '/img/wh-1000xm4.jpg', lotInfo: 'Лот #282828, доступно 12 штук', shippingInfo: 'Быстрая доставка', price: 300, category: 'Наушники' },
        { id: 29, title: 'HP Spectre x360', description: '13.3-inch, Intel Core i7, 16GB RAM, 512GB SSD', image: '/img/hp-spectre-x360.jpg', lotInfo: 'Лот #292929, доступно 6 штук', shippingInfo: 'Стандартная доставка', price: 1400, category: 'Ноутбук' },
        { id: 30, title: 'Amazon Kindle Paperwhite', description: '8GB, Waterproof, Ad-Supported', image: '/img/kindle-paperwhite.jpg', lotInfo: 'Лот #303030, доступно 20 штук', shippingInfo: 'Доставка 1-3 рабочих дня', price: 130, category: 'Электронная книга' },
        { id: 31, title: 'Asus ROG Strix Scar 15', description: '15.6-inch, Intel Core i9, 32GB RAM, 1TB SSD, RTX 3080', image: '/img/asus-rog-strix-scar-15.jpg', lotInfo: 'Лот #313131, доступно 3 штуки', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 2500, category: 'Ноутбук' },
        { id: 32, title: 'Garmin Fenix 6 Pro', description: 'Multisport GPS Watch, Black', image: '/img/garmin-fenix-6-pro.jpg', lotInfo: 'Лот #323232, доступно 10 штук', shippingInfo: 'Доставка 2-4 рабочих дня', price: 600, category: 'Умные часы' },
        { id: 33, title: 'Apple HomePod Mini', description: 'Smart Speaker, Space Gray', image: '/img/homepod-mini.jpg', lotInfo: 'Лот #333333, доступно 15 штук', shippingInfo: 'Бесплатная доставка', price: 100, category: 'Умный дом' },
        { id: 34, title: 'Sony A7 III', description: 'Full-Frame Mirrorless Camera, 24MP, 4K Video', image: '/img/sony-a7-iii.jpg', lotInfo: 'Лот #343434, доступно 5 штук', shippingInfo: 'Доставка 5-7 рабочих дней', price: 2000, category: 'Фото Камера' },
        { id: 35, title: 'Apple MacBook Air', description: '13-inch, Apple M1 Chip, 8GB RAM, 256GB SSD', image: '/img/macbook-air.jpg', lotInfo: 'Лот #353535, доступно 7 штук', shippingInfo: 'Бесплатная доставка', price: 1000, category: 'Ноутбук' },
        { id: 36, title: 'DJI Mavic Air 2', description: 'Foldable Drone with 4K Camera', image: '/img/dji-mavic-air-2.jpg', lotInfo: 'Лот #363636, доступно 5 штук', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 800, category: 'Дрон' },
        { id: 37, title: 'Apple iPad Pro', description: '11-inch, 256GB, Space Gray', image: '/img/ipad-pro.jpg', lotInfo: 'Лот #373737, доступно 4 штуки', shippingInfo: 'Бесплатная доставка', price: 900, category: 'Планшет' },
        { id: 38, title: 'Canon PowerShot G7 X Mark III', description: 'Compact Digital Camera, 20.1MP, 4K Video', image: '/img/canon-g7x-mark-iii.jpg', lotInfo: 'Лот #383838, доступно 6 штук', shippingInfo: 'Доставка 5-7 рабочих дней', price: 750, category: 'Фото Камера' },
        { id: 39, title: 'Samsung Odyssey G9', description: '49-inch Curved Gaming Monitor, QLED, 240Hz', image: '/img/samsung-odyssey-g9.jpg', lotInfo: 'Лот #393939, доступно 3 штуки', shippingInfo: 'Бесплатная доставка', price: 1300, category: 'Монитор' },
        { id: 40, title: 'Razer Blade 15', description: '15.6-inch, Intel Core i7, 16GB RAM, 512GB SSD, RTX 3070', image: '/img/razer-blade-15.jpg', lotInfo: 'Лот #404040, доступно 4 штуки', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 2200, category: 'Ноутбук' },
        { id: 41, title: 'Google Nest Hub Max', description: '10-inch Smart Display with Google Assistant', image: '/img/nest-hub-max.jpg', lotInfo: 'Лот #414141, доступно 10 штук', shippingInfo: 'Бесплатная доставка', price: 230, category: 'Умный дом' },
        { id: 42, title: 'HyperX Cloud II', description: 'Gaming Headset, 7.1 Surround Sound, Red', image: '/img/hyperx-cloud-ii.jpg', lotInfo: 'Лот #424242, доступно 15 штук', shippingInfo: 'Доставка 2-4 рабочих дня', price: 100, category: 'Наушники' },
        { id: 43, title: 'Samsung Galaxy Z Fold 3', description: '7.6-inch Foldable Dynamic AMOLED, 12GB RAM, 256GB Storage, Phantom Black', image: '/img/galaxy-z-fold-3.jpg', lotInfo: 'Лот #434343, доступно 4 штуки', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 1800, category: 'моб.Телефон' },
        { id: 44, title: 'Alienware Aurora R10', description: 'Gaming Desktop, AMD Ryzen 9, 32GB RAM, 1TB SSD, RTX 3080', image: '/img/alienware-aurora-r10.jpg', lotInfo: 'Лот #444444, доступно 3 штуки', shippingInfo: 'Стандартная доставка', price: 2800, category: 'ПК' },
        { id: 45, title: 'Apple Magic Keyboard', description: 'Wireless, with Numeric Keypad, US English - Silver', image: '/img/magic-keyboard.jpg', lotInfo: 'Лот #454545, доступно 10 штук', shippingInfo: 'Доставка 1-3 рабочих дня', price: 150, category: 'Аксессуары' },
        { id: 46, title: 'Sony Bravia XR', description: '65-inch OLED 4K Ultra HD Smart Google TV', image: '/img/sony-bravia-xr.jpg', lotInfo: 'Лот #464646, доступно 4 штуки', shippingInfo: 'Бесплатная доставка', price: 2000, category: 'Телевизор' },
        { id: 47, title: 'Logitech G Pro Wireless', description: 'Gaming Mouse with Esports Grade Performance', image: '/img/g-pro-wireless.jpg', lotInfo: 'Лот #474747, доступно 12 штук', shippingInfo: 'Доставка 1-3 рабочих дня', price: 150, category: 'Аксессуары' },
        { id: 48, title: 'Samsung Galaxy Watch 4', description: '44mm, Silver', image: '/img/galaxy-watch-4.jpg', lotInfo: 'Лот #484848, доступно 10 штук', shippingInfo: 'Бесплатная доставка', price: 250, category: 'Умные часы' },
        { id: 49, title: 'Bose SoundLink Revolve+', description: 'Portable and Long-Lasting Bluetooth 360 Speaker', image: '/img/soundlink-revolve-plus.jpg', lotInfo: 'Лот #494949, доступно 8 штук', shippingInfo: 'Экспресс-доставка за 1-2 дня', price: 300, category: 'Аудио' },
        { id: 50, title: 'Google Pixel Buds A-Series', description: 'True Wireless Earbuds, Clearly White', image: '/img/pixel-buds-a-series.jpg', lotInfo: 'Лот #505050, доступно 20 штук', shippingInfo: 'Доставка 2-4 рабочих дня', price: 100, category: 'Наушники' }
      ]);

    return (
        <ProductContext.Provider value={{ products }}>
            {children}
        </ProductContext.Provider>
    );
};

export const useProducts = () => useContext(ProductContext);
